import {
  LayoutDashboard,
  MessageSquare,
  Bot,
  Radio,
  Database,
  FileText,
  GitBranch,
  Wrench,
  Target,
  Clock,
  Activity,
  BarChart3,
  ScrollText,
  Settings,
  FileCode,
  Plug,
  ChevronLeft,
  PanelRightClose,
  PanelRightOpen,
  X,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  chat: MessageSquare,
  agent: Bot,
  channel: Radio,
  memory: Database,
  content: FileText,
  workflow: GitBranch,
  skill: Wrench,
  model: Target,
  cron: Clock,
  diagnostic: Activity,
  session: BarChart3,
  log: ScrollText,
  setting: Settings,
  template: FileCode,
  plugin: Plug,
  chevronLeft: ChevronLeft,
  panelClose: PanelRightClose,
  panelOpen: PanelRightOpen,
  close: X,
};

export type IconName = keyof typeof Icons;
